In [1]:
print('Hello, world') # shift누르고 엔터 -> 다음 셀이 자동으로 생성

Hello, world

# 판다스 객체 생성

- 시리즈(Series): 1차원 배열 ex)[1,2,3,4,5]
- 데이터프레임(DataFrame): 행과 열을 갖는 2차원 배열 (표) ex)엑셀을 생각해보자!

## 시리즈(Series) 만들기

### 판다스 라이브러리 불러오기

In [1]:
import pandas as pd

In [2]:
score = pd.Series([95, 90, 85, 90, 95])
score

0    95
1    90
2    85
3    90
4    95
dtype: int64

In [3]:
# 실수형 시리즈 만들기
s = pd.Series([4, 3.5, 3.8, 3, 3.7])
s

0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

### 인덱스 직접 지정

In [4]:
s = pd.Series([90, 80, 95], index=['A', 'B', 'C'])

In [5]:
s

A    90
B    80
C    95
dtype: int64

## 데이터프레임(DataFrame) 만들기

### 넘파이(numpy)로 배열 생성

In [ ]:
import numpy as np

arr = np.arange(12).reshape(4, 3)  # 행 4, 열 3
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [8]:
# 넘파이 배열을 데이터프레임으로
df = pd.DataFrame(arr)
df

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [9]:
print(df)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

### 딕셔너리로 데이터프레임 생성하기

In [10]:
df = pd.DataFrame({
    'name':['푸바오', '루이바오', '후이바오'],
    'score':[90, 80, 95],
    'dept':['com', 'eng', 'math']
})

In [11]:
df

   name  score  dept
0   푸바오     90   com
1  루이바오     80   eng
2  후이바오     95  math

### csv 파일 불러오기

In [12]:
df = pd.read_csv('mobile.csv')
df

     Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [13]:
df = pd.read_csv('mobile.csv', index_col=0)
df

          Color  price
Brand
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

# 판다스 데이터 확인

In [14]:
filename = 'weather.csv'
df = pd.read_csv(filename)
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df.shape  # (행, 열)

(3653, 4)

EDA (탐색적 데이터 분석)

## 앞에서부터 데이터 확인 - head()

In [16]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [17]:
df.head(12)

          date  temp  max_wind  mean_wind
0   2010-08-01  28.7       8.3        3.4
1   2010-08-02  25.2       8.7        3.8
2   2010-08-03  22.1       6.3        2.9
3   2010-08-04  25.3       6.6        4.2
4   2010-08-05  27.2       9.1        5.6
5   2010-08-06  26.8       9.8        8.0
6   2010-08-07  27.5       9.1        5.0
7   2010-08-08  26.6       5.9        4.0
8   2010-08-09  26.9       5.1        3.1
9   2010-08-10  25.6      10.2        5.5
10  2010-08-11  24.6       9.4        4.8
11  2010-08-12  23.7       8.7        2.6

## 데이터의 끝에서부터 확인 - tail()

In [18]:
df.tail()

            date  temp  max_wind  mean_wind
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [19]:
df.tail(2)

            date  temp  max_wind  mean_wind
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

## 데이터의 전반적인 정보를 알려준다 - info()

In [ ]:
df.info() # max_wind, mean_wind는 결측치가 있다

<class 'pandas.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       3653 non-null   str
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), str(1)
memory usage: 114.3 KB

## 인덱스 출력 - index

In [21]:
df.index

RangeIndex(start=0, stop=3653, step=1)

## 컬럼(열) 출력 - columns

In [22]:
df.columns

Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='str')

## 요약 통계량 - describe()

In [ ]:
df.describe() # 숫자형의 자료가 나온다

              temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

### 기온(temp) 컬럼의 평균

- 데이터프레임명[컬럼명].mean()

In [24]:
df['temp'].mean()

np.float64(12.942102381604162)

In [25]:
print(df['temp'].mean())

12.942102381604162

### 기온(temp) 컬럼의 내용들

In [26]:
df['temp']

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [ ]:
df['temp'].sum()  # 합계

np.float64(47277.5)

In [ ]:
df['temp'].median() # 중앙값(중간값)

np.float64(13.8)

In [29]:
df['temp'].std()  # 표준편차

np.float64(8.538507014753446)

In [30]:
df['temp'].var()  # 분산

np.float64(72.90610204099379)

In [31]:
df['temp'].max()  # 최대값

np.float64(31.3)

In [32]:
df['temp'].min()  # 최소값

np.float64(-9.0)

## 데이터를 크기순으로 정렬 - sort_values()

- ascending=True (생략) --> 오름차순
- ascending=False --> 내림차순
- by=[컬럼명]

In [33]:
# 최대 풍속(max_wind) 데이터 크기에 따라 오름차순으로 정렬

df.sort_values(by='max_wind', ascending=True)

            date  temp  max_wind  mean_wind
1514  2014-09-23  20.7       2.0        1.0
1134  2013-09-08  20.4       2.1        0.8
421   2011-09-26  18.7       2.1        0.3
1005  2013-05-02   7.1       2.2        0.8
1512  2014-09-21  20.4       2.2        1.2
...          ...   ...       ...        ...
2988  2018-10-06  19.4      26.0        7.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [34]:
# 최대 풍속(max_wind) 데이터 크기에 따라 내림차순으로 정렬

df.sort_values(by='max_wind', ascending=False)

            date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

## 빈도 분석 결과 - value_counts()

In [35]:
filename = 'bank.csv'
bank = pd.read_csv(filename)
bank.head()

           job  education  balance  duration   y
0   management   tertiary     2143       261  no
1   technician  secondary      265       348  no
2  blue-collar  secondary       -7       365  no
3   technician  secondary       -3      1666  no
4   technician  secondary     -103       145  no

In [ ]:
bank['job'].value_counts() # 내림차순(기본값)

job
management       1560
blue-collar      1499
technician       1206
admin.            834
services          661
retired           351
self-employed     256
entrepreneur      239
unemployed        223
housemaid         208
student           153
Name: count, dtype: int64

In [37]:
bank['job'].value_counts(ascending=True)  # 오름차순

job
student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: count, dtype: int64

## 해당 열의 고유값 보기 - unique()

In [38]:
bank['job'].unique()

<StringArray>
[   'management',    'technician',   'blue-collar',       'retired',
      'services',        'admin.',  'entrepreneur', 'self-employed',
    'unemployed',       'student',             nan,     'housemaid']
Length: 12, dtype: str