# 판다스 데이터 가공하기

In [2]:
import pandas as pd
import numpy as np

filename = 'dust1.xlsx'
dust = pd.read_excel(filename)
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

## 컬럼(열, 변수, 피처) 삭제 / 생성

### drop(컬럼명, axis=1) --> 컬럼(열) 삭제

- drop(..., axis=0) --> 행 삭제 (axis=0은 생략가능)

In [3]:
# 지역, 망, 측정소코드 삭제

dust.drop(['지역', '망', '측정소코드'], axis=1)

   측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0   송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1   송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2   송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3   송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4   송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236
5   송파구  2021040106  0.004  0.7  0.002  0.051    38    18  서울 송파구 백제고분로 236
6   송파구  2021040107  0.003  0.7  0.003  0.052    38    17  서울 송파구 백제고분로 236
7   송파구  2021040108  0.004  0.8  0.004  0.057    42    20  서울 송파구 백제고분로 236
8   송파구  2021040109  0.004  0.6  0.014  0.046    45    22  서울 송파구 백제고분로 236
9   송파구  2021040110  0.003  0.4  0.028  0.033    44    16  서울 송파구 백제고분로 236
10  송파구  2021040111  0.003  0.3  0.048  0.014    38    15  서울 송파구 백제고분로 236
11  송파구  2021040112  0.003  0.3  0.053  0.012    39    11  서울 송파구 백제고분로 236
12  송파구  2021040113  0.003  0.3  0.056  0.010    44    13  서울 송파구 백제고분로 236
13  송파구  2021040114  0.003  0.3  0.057  0.011    42    14  서울 송파구 백제고분로 236
14  송파구  2021040115  0.003  0.3  0.057  0.013    44    10  서울 송파구 백제고분로 236
15  송파구  2021040116  0.003  0.3  0.060  0.012    45    11  서울 송파구 백제고분로 236
16  송파구  2021040117  0.003  0.4  0.058  0.015    59    10  서울 송파구 백제고분로 236
17  송파구  2021040118  0.003  0.4  0.052  0.018    68    11  서울 송파구 백제고분로 236
18  송파구  2021040119  0.003  0.4  0.049  0.017    59    10  서울 송파구 백제고분로 236
19  송파구  2021040120  0.003  0.4  0.045  0.019    48     8  서울 송파구 백제고분로 236
20  송파구  2021040121  0.003  0.4  0.047  0.016    44     9  서울 송파구 백제고분로 236
21  송파구  2021040122  0.003  0.4  0.046  0.016    41     9  서울 송파구 백제고분로 236
22  송파구  2021040123  0.003  0.4  0.043  0.017    46    14  서울 송파구 백제고분로 236
23  송파구  2021040124  0.002  0.4  0.047  0.013    46    12  서울 송파구 백제고분로 236
24  송파구  2021040201  0.003  0.3  0.048  0.011    44    15  서울 송파구 백제고분로 236
25  송파구  2021040202  0.003  0.3  0.049  0.010    45    11  서울 송파구 백제고분로 236
26  송파구  2021040203  0.003  0.3  0.051  0.009    47    10  서울 송파구 백제고분로 236
27  송파구  2021040204  0.003  0.3  0.050  0.009    45    11  서울 송파구 백제고분로 236
28  송파구  2021040205  0.002  0.3  0.050  0.010    44    13  서울 송파구 백제고분로 236
29  송파구  2021040206  0.003  0.3  0.044  0.015    42    11  서울 송파구 백제고분로 236
30  송파구  2021040207  0.002  0.4  0.039  0.020    40     9  서울 송파구 백제고분로 236
31  송파구  2021040208  0.003  0.4  0.030  0.031    43    12  서울 송파구 백제고분로 236

In [4]:
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [5]:
dust = dust.drop(['지역', '망', '측정소코드'], axis=1)

dust.head()

  측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

### 컬럼 생성하기(추가)

- 데이터프레임명[추가하고 싶은 컬럼명] = 값

In [6]:
dust['city'] = '서울'

In [7]:
dust.head()

,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,city
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

## 컬럼 이름 수정 --> rename()

- 데이터프레임명.rename(columns={'기존이름':'새이름'})

In [9]:
dust = dust.rename(columns={
    '측정소명':'name',
    '측정일시':'date',
    '주소':'addr'
})

In [10]:
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'addr',
       'city'],
      dtype='str')

## 데이터 형 확인 --> dtypes

In [ ]:
dust.dtypes  # 판다스 3버전부터 object -> str 변경

name        str
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr        str
city        str
dtype: object

## 데이터 형 변환 --> astype()

- 컬럼명.astype(바꿀 자료형)

In [13]:
dust['date'].astype(str)

0     2021040101
1     2021040102
2     2021040103
3     2021040104
4     2021040105
5     2021040106
6     2021040107
7     2021040108
8     2021040109
9     2021040110
10    2021040111
11    2021040112
12    2021040113
13    2021040114
14    2021040115
15    2021040116
16    2021040117
17    2021040118
18    2021040119
19    2021040120
20    2021040121
21    2021040122
22    2021040123
23    2021040124
24    2021040201
25    2021040202
26    2021040203
27    2021040204
28    2021040205
29    2021040206
30    2021040207
31    2021040208
Name: date, dtype: str

In [14]:
dust['date'] = dust['date'].astype(str)

In [15]:
dust.dtypes

name        str
date        str
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr        str
city        str
dtype: object

In [16]:
dust['date']

0     2021040101
1     2021040102
2     2021040103
3     2021040104
4     2021040105
5     2021040106
6     2021040107
7     2021040108
8     2021040109
9     2021040110
10    2021040111
11    2021040112
12    2021040113
13    2021040114
14    2021040115
15    2021040116
16    2021040117
17    2021040118
18    2021040119
19    2021040120
20    2021040121
21    2021040122
22    2021040123
23    2021040124
24    2021040201
25    2021040202
26    2021040203
27    2021040204
28    2021040205
29    2021040206
30    2021040207
31    2021040208
Name: date, dtype: str

In [17]:
# 첫 8자리만 자른다 --> slice()
dust['date'] = dust['date'].str.slice(0, 8)

## to_datetime() --> 날짜/시간 형으로 변환 (시계열)

In [18]:
pd.to_datetime(dust['date'])

0    2021-04-01
1    2021-04-01
2    2021-04-01
3    2021-04-01
4    2021-04-01
5    2021-04-01
6    2021-04-01
7    2021-04-01
8    2021-04-01
9    2021-04-01
10   2021-04-01
11   2021-04-01
12   2021-04-01
13   2021-04-01
14   2021-04-01
15   2021-04-01
16   2021-04-01
17   2021-04-01
18   2021-04-01
19   2021-04-01
20   2021-04-01
21   2021-04-01
22   2021-04-01
23   2021-04-01
24   2021-04-02
25   2021-04-02
26   2021-04-02
27   2021-04-02
28   2021-04-02
29   2021-04-02
30   2021-04-02
31   2021-04-02
Name: date, dtype: datetime64[us]

In [19]:
dust['date'] = pd.to_datetime(dust['date'])
dust.dtypes

name               str
date    datetime64[us]
SO2            float64
CO             float64
O3             float64
NO2            float64
PM10             int64
PM25             int64
addr               str
city               str
dtype: object