In [1]:
# 라이브러리 불러오기

import pandas as pd
import numpy as np

In [2]:
dust = pd.read_excel('dust1.xlsx')
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [3]:
# 컬럼 이름 변경

dust = dust.rename(columns={'측정일시':'date'})
dust.head()

,지역,망,측정소코드,측정소명,date,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [4]:
# 자료형 확인

dust.dtypes

지역           str
망            str
측정소코드      int64
측정소명         str
date       int64
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
dtype: object

In [5]:
# 문자열로 형 변환

dust['date'] = dust['date'].astype(str)
dust['date'] = dust['date'].str.slice(0, 8)
dust.dtypes

지역           str
망            str
측정소코드      int64
측정소명         str
date         str
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
dtype: object

In [6]:
# 날짜형으로 형 변환

dust['date'] = pd.to_datetime(dust['date'])
dust.dtypes

지역                  str
망                   str
측정소코드             int64
측정소명                str
date     datetime64[us]
SO2             float64
CO              float64
O3              float64
NO2             float64
PM10              int64
PM25              int64
주소                  str
dtype: object

# 날짜형을 년, 월, 일로 분리 추출

In [7]:
# dt 속성

dust['date'].dt

In [ ]:
dust['date'].dt.year  # 연도 추출

0     2021
1     2021
2     2021
3     2021
4     2021
5     2021
6     2021
7     2021
8     2021
9     2021
10    2021
11    2021
12    2021
13    2021
14    2021
15    2021
16    2021
17    2021
18    2021
19    2021
20    2021
21    2021
22    2021
23    2021
24    2021
25    2021
26    2021
27    2021
28    2021
29    2021
30    2021
31    2021
Name: date, dtype: int32

## 년, 월, 일 컬럼을 생성

In [9]:
dust['year'] = dust['date'].dt.year  # 연도 추출
dust['month'] = dust['date'].dt.month  # 월 추출
dust['day'] = dust['date'].dt.day  # 일 추출

In [10]:
dust.head()

,지역,망,측정소코드,측정소명,date,SO2,CO,O3,NO2,PM10,PM25,주소,year,month,day
0,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,2021,4,1
1,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,2021,4,1
2,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,2021,4,1
3,서울 송파구,도시대기,111273,송파구,2021-04-01,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,2021,4,1
4,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,2021,4,1

# 데이터 병합

In [11]:
s1 = pd.read_excel('nation.xlsx')
s2 = pd.read_excel('code.xlsx')

In [12]:
s1.head(2)

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000

In [13]:
s2.head(2)

  국적코드  국적명
0  A01  필리핀
1  A02   일본

## pd.merge() 함수

- pd.merge(데이터프레임1, 데이터프레임2, on=기준컬럼명, how='inner')
- how에는 'outer', 'left', 'right' 도 가능

In [14]:
# 국적 코드 컬럼 기준

pd.merge(s1, s2, on='국적코드')

  국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

In [17]:
s1

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000
2  A05  남성     300     10
3  A05  여성     200     50
4  A06  남성  158912  24486
5  A06  여성  325000  63466

In [16]:
s2

  국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주
5  A06  베트남
6  A07  스위스
7  A99   기타

In [18]:
# 오른쪽 컬럼 기준 (ex.차집합)

pd.merge(s1, s2, how='right', on='국적코드')

   국적코드   성별      입국객수      증가수  국적명
0   A01   남성  125000.0   8000.0  필리핀
1   A01   여성  130000.0  10000.0  필리핀
2   A02  NaN       NaN      NaN   일본
3   A03  NaN       NaN      NaN   미국
4   A04  NaN       NaN      NaN   중국
5   A05   남성     300.0     10.0   호주
6   A05   여성     200.0     50.0   호주
7   A06   남성  158912.0  24486.0  베트남
8   A06   여성  325000.0  63466.0  베트남
9   A07  NaN       NaN      NaN  스위스
10  A99  NaN       NaN      NaN   기타

# 데이터 그룹핑

## groupby()

In [ ]:
# 국적코드별 성별, 입국객수, 증가수
s1.groupby('국적코드').sum()

        성별    입국객수    증가수
국적코드
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [21]:
# 국적코드별, 성별 --> 입국객수, 증가수
# 그룹을 2개
s1.groupby(['국적코드', '성별']).sum()

           입국객수    증가수
국적코드 성별
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

# 연습문제 2

In [22]:
df = pd.read_csv('covid.csv', encoding='cp949') 
df

       항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0
5    잡지·책  776  31.3  17.8  50.9
6    종이신문  552  17.6  23.2  59.2

In [23]:
df = pd.read_csv('covid.csv', index_col=0, encoding='cp949') 
df

        사례수    증가    감소  변화없음
항목
스마트폰    999  78.9   1.7  19.4
텔레비전    965  68.5   3.9  27.6
개인용 PC  973  65.7   3.7  30.6
태블릿 PC  662  46.8   4.2  49.0
라디오     687  35.5  12.5  52.0
잡지·책    776  31.3  17.8  50.9
종이신문    552  17.6  23.2  59.2

In [27]:
# 사례수가 가장 높은 것
df['사례수'].max()

np.int64(999)

In [28]:
# 스마트폰이 가장 높다 -> 그 행 다 추출
df['사례수'] == df['사례수'].max()

항목
스마트폰       True
텔레비전      False
개인용 PC    False
태블릿 PC    False
라디오       False
잡지·책      False
종이신문      False
Name: 사례수, dtype: bool

In [29]:
df[df['사례수'] == df['사례수'].max()]

      사례수    증가   감소  변화없음
항목
스마트폰  999  78.9  1.7  19.4

In [30]:
# 증가율이 높은 3개 --> 정렬 --> 내림차순
df.sort_values(by='증가', ascending=False)

        사례수    증가    감소  변화없음
항목
스마트폰    999  78.9   1.7  19.4
텔레비전    965  68.5   3.9  27.6
개인용 PC  973  65.7   3.7  30.6
태블릿 PC  662  46.8   4.2  49.0
라디오     687  35.5  12.5  52.0
잡지·책    776  31.3  17.8  50.9
종이신문    552  17.6  23.2  59.2

In [31]:
df2 = df.sort_values(by='증가', ascending=False)
df2.head(3)

        사례수    증가   감소  변화없음
항목
스마트폰    999  78.9  1.7  19.4
텔레비전    965  68.5  3.9  27.6
개인용 PC  973  65.7  3.7  30.6

# 연습문제 3

### 필드 == 컬럼 == 열

In [34]:
vaccine = pd.read_csv('vaccine.csv')
vaccine.tail()

,date,subject,day1num,day1sum,day1rate,day2num,day2sum,day2rate
174,2021.04.25,1023346,23323,350631,34.2,3411,18513,1.8
175,2021.04.24,1023346,200,350427,34.2,0,18513,1.8
176,2021.04.23,1027740,10195,345764,33.6,119,18376,1.8
177,2021.04.22,1023538,27074,317386,31.0,2479,15901,1.6
178,2021.04.21,1019322,22501,291857,28.6,2358,13543,1.3

In [35]:
# 필요없는 열을 삭제 
vaccine.drop(['day1sum', 'day1rate', 'day2sum', 'day2rate'], axis=1)

           date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

[179 rows x 4 columns]

In [36]:
vaccine = vaccine.drop(['day1sum', 'day1rate', 'day2sum', 'day2rate'], axis=1)

In [37]:
# 기초통계량 - describe()
vaccine.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [38]:
vaccine.head()

         date  subject  day1num  day2num
0  2021.10.16  9505868    10673    66910
1  2021.10.15  9505868    14556   133580
2  2021.10.14  9505868     9609    94569
3  2021.10.13  9505868     9804    77503
4  2021.10.12  9505868    17274   110204

In [39]:
vaccine.info()

<class 'pandas.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     179 non-null    str
 1   subject  179 non-null    int64
 2   day1num  179 non-null    int64
 3   day2num  179 non-null    int64
dtypes: int64(3), str(1)
memory usage: 5.7 KB

In [40]:
# 날짜형으로 형 변환
vaccine['date'] = pd.to_datetime(vaccine['date'])
vaccine.info()

<class 'pandas.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     179 non-null    datetime64[us]
 1   subject  179 non-null    int64
 2   day1num  179 non-null    int64
 3   day2num  179 non-null    int64
dtypes: datetime64[us](1), int64(3)
memory usage: 5.7 KB

In [41]:
# month라는 이름의 컬럼을 생성
vaccine['month'] = vaccine['date'].dt.month
vaccine.head(10)

        date  subject  day1num  day2num  month
0 2021-10-16  9505868    10673    66910     10
1 2021-10-15  9505868    14556   133580     10
2 2021-10-14  9505868     9609    94569     10
3 2021-10-13  9505868     9804    77503     10
4 2021-10-12  9505868    17274   110204     10
5 2021-10-11  9505868    16395    28099     10
6 2021-10-10  9505868    16395    28099     10
7 2021-10-09  9505868      330    15337     10
8 2021-10-08  9505868     1373    15337     10
9 2021-10-07  9505868     6847   200186     10

In [43]:
# 월별 day1num, day2num
vaccine2 = vaccine[['day1num', 'day2num', 'month']]
vaccine2.head()

   day1num  day2num  month
0    10673    66910     10
1    14556   133580     10
2     9609    94569     10
3     9804    77503     10
4    17274   110204     10

In [44]:
vaccine2.groupby('month').mean()

            day1num       day2num
month
4      22060.100000   2304.600000
5      18225.548387   9734.000000
6      55957.200000  20147.300000
7      25807.870968   9934.903226
8      57667.258065  55575.000000
9      65715.000000  62162.000000
10      9406.312500  79900.750000

# 연습문제4

In [49]:
df1 = pd.read_csv('signup.csv', encoding='cp949')
df1

   수강코드    과목명 담당교수
0   111    파이썬  양숙희
1   222  데이터분석  오경선
2   333   인공지능  장은실
3   444   선형대수  황복동
4   555   이산수학  정명식
5   666  컴퓨터개론  최봉수
6   777   자료구조  김진영
7   888   정보통신  김진호

In [50]:
df2 = pd.read_csv('professor.csv', encoding='cp949')
df2

  담당교수     학과
0  양숙희  컴퓨터공학
1  장은실   정보통신
2  오경선   인공지능
3  황복동  컴퓨터공학
4  정명식   인공지능

In [51]:
df = pd.merge(df1, df2, on='담당교수')
df

   수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [53]:
# 학과별 인원수 --> 그룹 --> count()
df = df[['담당교수', '학과']]
df.groupby('학과').count()

       담당교수
학과
인공지능      2
정보통신      1
컴퓨터공학     2

In [ ]:
# git bash --> 리눅스 명령어
# 명령 프롬프트 --> 윈도우 명령
# 가상환경 잡는거 --> hello.py --> 터미널 출력
# git add --> commit --> push
# branch